### ISSUE TITLE
Cannot find protocol declaration for nsobject

### ISSUE THREAD

**Issue by fuermosi777** [cwRichardKim/RKSwipeBetweenViewControllers#11]
Hi Richard, 
I dragged .h and .m files into my directory and an error said "cannot find protocol declaration for NSObject". I checked that the `@protocol RKSwipeBetweenViewControllersDelegate` following with a `<NSObject>`. After deleting that everything was fine.

**Comment by cwRichardKim** [comment]
interesting, thanks for letting me know i'll look into it

**Comment by jlippold** [comment]
move `#import <UIKit/UIKit.h>` above the `@protocol RKSwipeBetweenViewControllersDelegate <NSObject>`

**Comment by cwRichardKim** [comment]
done
