### ISSUE TITLE
Clunk Control. 

### ISSUE THREAD

**Issue by MHaroonBaig** [cwRichardKim/RKSwipeBetweenViewControllers#12]
It'd be really great if you use the Accelerometer and Gyroscope to swipe between the views with just a Clunk or a slight jerk. I've written a very nice wrapper around CoreMotion Framework too.
https://github.com/MHaroonBaig/MotionKit

**Comment by cwRichardKim** [comment]
I appreciate the suggestion, but I'm not sure if people will appreciate that, especially because there are a few cocoa pod users (who will automatically get the update). It seems like an entirely different repo!
