### ISSUE TITLE
How can I move the tab to bottom?

### ISSUE THREAD

**Issue by dickfalaDeveloper** [cwRichardKim/RKSwipeBetweenViewControllers#17]
I found you use navigationBar . So the Tab button will put top at screen.
But I want to move the tab to the bottom. Can I move the navigation bar to bottom?
If I move the navigation bar to the bottom at screen, the Apple will reject the app?
Thank you.

**Comment by cwRichardKim** [comment]
Sorry you can’t, it’s a navigation controller =/ you could examine the code and try to build another custom controller that does something similar
