### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by hhanesand** [cwRichardKim/RKSwipeBetweenViewControllers#29]
The fact that you have to modify the implementation is completely ridiculous, because that negates all the advantages of using source control. If you push a change to git, there is no way for us to receive the update without manually adding it in ourselves in our heavily modified implementations. It would be much better if all of the private customization properties were exposed in the implementation so customization could be done from another class.

I appreciate your work here, but I think this library would be much better off if these changes were made.

**Comment by cwRichardKim** [comment]
agreed. I'm planning on redoing this when i have time. Thanks for bringing this up
