### ISSUE TITLE
Method 'syncScrollView'

### ISSUE THREAD

**Issue by LeeKyungMoon** [cwRichardKim/RKSwipeBetweenViewControllers#31]
the method 'syncScrollView' has this code below:
    for (UIView* view in pageController.view.subviews){
        if([view isKindOfClass:[UIScrollView class]])
        {
            pageScrollView = (UIScrollView *)view;
            pageScrollView.delegate = self;
        }
    }

What I can not undestand is that how there is the view whose class is 'UIScrollView'
Programmer set pageController's viewcontrollers so there might not be a uiscrollview.
But it always pass that code 'if([view isKindOfClass:[UIScrollView class]])'
I don't understand

**Comment by LeeKyungMoon** [comment]
The view I said above is _UIQueuingScrollView. How that can be born??

**Comment by cwRichardKim** [comment]
all pageviewcontrollers have a scrollview. that's how it scrolls from one page to another
